var car = 'subaru';
var age = 5;
var temperature = 25;
var isSunny = true;
var hasLicense = false;
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is age >= 18? I predict False.");
console.log(age >= 18);
console.log("Is temperature < 30? I predict True.");
console.log(temperature < 30);
console.log("Is isSunny && temperature > 20? I predict True.");
console.log(isSunny && temperature > 20);
console.log("Is temperature >= 30 || isSunny? I predict True.");
console.log(temperature >= 30 || isSunny);
console.log("Is hasLicense === true? I predict False.");
console.log(hasLicense = true);
console.log("Is age === '5'? I predict False.");
console.log(age === 5);
console.log("Is car !== 'honda'? I predict True.");
console.log(car !== 'honda');
console.log("Is temperature <= 20? I predict False.");
console.log(temperature <= 20);
console.log("Is isSunny || hasLicense? I predict True.");
console.log(isSunny || hasLicense);
